version: '3'

services:

  drone-server:
    image: drone/drone:0.8-alpine
    ports:
      - 443:443
      # - "${PRO_PUBLIC_IP}:8000:8000"
    # volumes:
    #   - drone-data:/var/lib/drone/:rw
    #   - ./conf.d/ssl:/etc/certs:rw
    restart: always
    environment:
      - DRONE_SECRET=drone
      - DRONE_OPEN=false
      - DRONE_ADMIN=ski2004
      - DRONE_HOST=aa.test.net
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=ac8d94e73d649a6cbeab
      - DRONE_GITHUB_SECRET=efc9bdf9d42c9f62ebe1afd27dba174aa33d7d73
      - DRONE_SERVER_CERT=/etc/certs/drone.domain.com.crt
      - DRONE_SERVER_KEY=/etc/certs/drone.domain.com.key

  drone-agent:
    image: drone/agent:0.8-alpine
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DRONE_SECRET=drone
      - DRONE_SERVER=drone-server:9000
    dns: 114.114.114.114

volumes:
  drone-data: