version: '3'

services:

  drone-server:
    image: drone/drone:0.8-alpine
    ports:
      - 80:8000
      # - "${PRO_PUBLIC_IP}:8000:8000"
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=890046c6217d55167794
      - DRONE_GITHUB_SECRET=4adf71aaa8d5260d96b09dad4ad25cd3d7587892
      - DRONE_SECRET=drone

  drone-agent:
    image: drone/agent:0.8-alpine
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DRONE_SECRET=drone
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
